# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia 
os:
  - linux
  - osx
julia:
  - 1.5.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - julia dependencies.jl
  - julia test/runtests.jl