environment:
  matrix:
  - julia_version: 1.5.3
  - julia_version: nightly

platform:
  - x86 # 32-bit
  - x64 # 64-bit

matrix:
  allow_failures:
  - julia_version: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - C:\julia\bin\julia dependencies.jl

test_script:
  - C:\julia\bin\julia test/runtests.jl