environment:
  matrix:
  - julia_version: 1.6.1
  - julia_version: nightly

platform:
  - x86 # 32-bit
  - x64 # 64-bit

matrix:
  allow_failures:
  - julia_version: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - set CONDA_JL_VERSION=3
  - C:\julia\bin\julia -e "using Pkg; Pkg.add(String(`"PyCall`")); Pkg.add(String(`"PyPlot`"))"
  - C:\julia\bin\julia -e "using Pkg; Pkg.add(["Plots", "DataFrames", "CSV"])"
  - C:\julia\bin\julia -e "using Pkg; Pkg.add(["Test", "StatsPlots", "Statistics"])"
  - C:\julia\bin\julia -e "using Pkg; Pkg.add(["FreqTables", "NamedArrays", "Distributions"])"
  - C:\julia\bin\julia -e "using Pkg; Pkg.add(["LinearAlgebra", "StatsBase"])"
  - set PYTHON=""
  - C:\julia\bin\julia -e "using Pkg; Pkg.add("Conda"); Pkg.update(); Pkg.build("PyCall"); using PyPlot"

test_script:
  - C:\julia\bin\julia test/runtests.jl