FROM julia:1.5.3

RUN apt-get update

RUN apt-get -yq install libxt6 libxrender1 libxext6 libgl1-mesa-glx libqt5widgets5

RUN apt-get -yq install build-essential

RUN apt-get -yq install git

RUN git config --global user.name Shisato

RUN git config --global user.email shisatoyano@gmail.com