name: Linux_CI



on: [push, pull_request]



jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:

      matrix:

        julia-version: ['1.6']

        os: [ubuntu-latest]

    

    steps:
      - uses: actions/checkout@v1.0.0

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: "Update"
        run: sudo apt-get update
      
      - name: "Upgrade"
        run: sudo apt-get upgrade

      - name: "Install packages"
        run: julia -e 'ENV["CONDA_JL_VERSION"]=3;include("setup.jl");Setup.install_packages()'

      - name: "Install matplotlib"
        run: julia -e 'ENV["PYTHON"]=""; using Pkg; Pkg.add("Conda"); Pkg.update(); Pkg.build("PyCall"); using PyPlot'
        shell: bash

      - name: "Run test suite"
        run: julia --code-coverage test/runtests.jl
      
      - name: "Upload coverage"
      
        run: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'