name: Linux_CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [1.5.x]

    name: Julia ${{ matrix.julia-version }} CI

    steps:
    - name: Install dependencies
      run: julia packages.jl
    - name: Run test suite
      run: julia runtests.jl
